INSERT INTO product (productPrice, productText, productName, productCategory, productImg, productQuantity)
values (19.99, 'Text', 'GREEN LABEL Whey Protein','Champion Green Line', '250pgreen',25);


INSERT INTO user (userEmail,userName,userSurname,userPassword, userIsAdmin)
values ('email1@gmail.com', 'Giovanna', 'Giorno', 'PASSWORD1', 0);

INSERT INTO user (userEmail,userName,userSurname,userPassword, userIsAdmin)
values ('email2@gmail.com', 'Anna', 'Volta', 'PASSWORD1', 0);